In [24]:
import warnings
warnings.simplefilter("ignore", UserWarning)
import pandas as pd
import os

In [25]:
parent_directory = 'mar_2024_results'

In [26]:
result_directory = 'mar_2024_results\\gpt_results\\Refugees'

In [27]:
setting_of_interest = 'GPT4o_Ref'

In [28]:
dfs = []

In [29]:
for i in os.listdir(parent_directory):
	if i == 'v6_cot':
		child_dir = f'{parent_directory}//{i}'
		for item in os.listdir(child_dir):
			if item.startswith(setting_of_interest):
				df = pd.read_csv(f'{child_dir}//{item}', index_col=0)
				df.reset_index(inplace=True)
				df.columns = ['category', 'precision', 'recall', 'f1-score', 'support']
				dfs.append(df)

In [30]:
cats = dfs[0].category.to_list()
per_category_results = {}
for cat in cats:
    res = []
    for df in dfs:
        res.append(df.loc[df.category == cat])
    res_df = pd.concat(res, axis=0)
    res_df.drop(columns='category', inplace=True)
    means = res_df.mean().to_dict()
    per_category_results[cat] = means
mean_per_run = pd.DataFrame(per_category_results).T
mean_per_run

                            precision    recall  f1-score     support
Advocacy                     0.727651  0.638710  0.668693   31.000000
Arguing                      0.401821  0.288000  0.325008   25.000000
Boundary policing            0.317736  0.670968  0.428603   31.000000
Celebration                  0.483206  0.600000  0.481685   12.000000
Coordination of assistance   0.440771  0.815385  0.570257   13.000000
Denouncing                   0.232917  0.566667  0.327185   24.000000
Expressing solidarity        0.521861  0.583333  0.543836   12.000000
Fundraising                  0.531127  0.980000  0.685738   10.000000
Knowledge performance        0.354832  0.218182  0.264366   22.000000
News and content curation    0.802693  0.590769  0.673597   65.000000
Not applicable               0.806375  0.485507  0.596819  138.000000
Personal anecdote            0.855455  0.600000  0.684444   10.000000
Self-criticism               0.303251  0.309091  0.261437   11.000000
Self-promotion               0.850000  0.123077  0.207731   13.000000
accuracy                     0.520863  0.520863  0.520863    0.520863
macro avg                    0.544978  0.533549  0.479957  417.000000
weighted avg                 0.636321  0.520863  0.529862  417.000000

In [31]:
mean_per_run.to_csv(f'{result_directory}\\{setting_of_interest}_mean.csv')

In [32]:
per_category_results = {}
for cat in cats:
    res = []
    for df in dfs:
        res.append(df.loc[df.category == cat])
    res_df = pd.concat(res, axis=0)
    res_df.drop(columns='category', inplace=True)
    stds = res_df.std().to_dict()
    per_category_results[cat] = stds
std_per_run = pd.DataFrame(per_category_results).T
std_per_run

                            precision    recall  f1-score   support
Advocacy                     0.048841  0.183049  0.121434  0.000000
Arguing                      0.170797  0.052154  0.079238  0.000000
Boundary policing            0.025751  0.135714  0.046554  0.000000
Celebration                  0.159433  0.223607  0.065020  0.000000
Coordination of assistance   0.077698  0.087706  0.080503  0.000000
Denouncing                   0.032993  0.100347  0.035022  0.000000
Expressing solidarity        0.123804  0.058926  0.086963  0.000000
Fundraising                  0.073446  0.044721  0.063175  0.000000
Knowledge performance        0.124917  0.081312  0.091830  0.000000
News and content curation    0.035803  0.113888  0.062229  0.000000
Not applicable               0.053127  0.111909  0.074580  0.000000
Personal anecdote            0.101444  0.187083  0.121480  0.000000
Self-criticism               0.209278  0.188513  0.080765  0.000000
Self-promotion               0.223607  0.068802  0.098122  0.000000
accuracy                     0.027416  0.027416  0.027416  0.027416
macro avg                    0.011582  0.026578  0.018762  0.000000
weighted avg                 0.020146  0.027416  0.026154  0.000000

In [33]:
std_per_run.to_csv(f'{result_directory}\\{setting_of_interest}_std.csv')