In [1]:
import warnings
warnings.simplefilter("ignore", UserWarning)
import pandas as pd
import os

In [2]:
result_directory = 'mar_2024_results\\v6_cot\\'

In [10]:
run_of_interest = 'GPT4_ESC_MPE_COT'
dfs = []
for file in os.listdir(result_directory):
	if file.startswith(run_of_interest) and 'std' and 'mean' not in file: #calculation is incorrect as it picks up everything
		print(file)
		df = pd.read_csv(f'{result_directory}\\{file}', index_col=0)
		df.reset_index(inplace=True)
		df.columns = ['category', 'precision', 'recall', 'f1-score', 'support']
		dfs.append(df)

GPT4_ESC_MPE_COT_0.csv
GPT4_ESC_MPE_COT_1.csv
GPT4_ESC_MPE_COT_2.csv
GPT4_ESC_MPE_COT_3.csv
GPT4_ESC_MPE_COT_4.csv

In [11]:
cats = dfs[0].category.to_list()

In [12]:
per_category_results = {}
for cat in cats:
	res = []
	for df in dfs:
		res.append(df.loc[df.category == cat])
	res_df = pd.concat(res, axis=0)
	res_df.drop(columns='category', inplace=True)
	means = res_df.mean().to_dict()
	per_category_results[cat] = means

In [13]:
mean_per_run = pd.DataFrame(per_category_results).T
mean_per_run

                           precision    recall  f1-score  support
Advocacy                    0.548645  0.700684  0.613223   10.600
Arguing                     0.268108  0.340449  0.299459   14.000
Audiencing                  0.663799  0.747092  0.701671   95.200
Betting                     0.880605  0.961450  0.916483   15.400
Charity                     0.704029  0.773939  0.732322   12.200
Community imagining         0.320952  0.201587  0.243197   12.200
Denouncing                  0.617143  0.675075  0.638953   12.400
Expressing emotions         0.518986  0.871195  0.642976   11.200
Expressing solidarity       0.568901  0.585130  0.573743   19.400
Knowledge performance       0.396313  0.376605  0.384964   23.000
News and content curation   0.790433  0.810732  0.800182   77.400
Not applicable              0.895876  0.505008  0.643516   86.200
Self-promotion              0.345344  0.626557  0.441849   10.800
accuracy                    0.655000  0.655000  0.655000    0.655
macro avg                   0.578395  0.628885  0.587118  400.000
weighted avg                0.691859  0.655000  0.655495  400.000

In [14]:
mean_per_run.to_csv(f'{result_directory}\\{run_of_interest}_mean.csv')

In [15]:
per_category_results = {}
for cat in cats:
    res = []
    for df in dfs:
        res.append(df.loc[df.category == cat])
    res_df = pd.concat(res, axis=0)
    res_df.drop(columns='category', inplace=True)
    stds = res_df.std().to_dict()
    per_category_results[cat] = stds
std_per_run = pd.DataFrame(per_category_results).T
std_per_run

                           precision    recall  f1-score   support
Advocacy                    0.038278  0.120116  0.062593  1.816590
Arguing                     0.085478  0.117722  0.098878  1.414214
Audiencing                  0.051314  0.034394  0.028027  6.140033
Betting                     0.089239  0.035489  0.042299  3.049590
Charity                     0.105860  0.096343  0.073531  1.643168
Community imagining         0.230537  0.117664  0.153303  2.489980
Denouncing                  0.168551  0.100364  0.129247  1.140175
Expressing emotions         0.130570  0.125248  0.116150  2.280351
Expressing solidarity       0.134917  0.141959  0.127748  3.209361
Knowledge performance       0.149524  0.135260  0.139720  3.674235
News and content curation   0.034932  0.029383  0.028014  5.412947
Not applicable              0.071975  0.036084  0.020930  7.120393
Self-promotion              0.160468  0.195332  0.182759  3.114482
accuracy                    0.031623  0.031623  0.031623  0.031623
macro avg                   0.050181  0.049304  0.051509  0.000000
weighted avg                0.020885  0.031623  0.032020  0.000000

In [16]:
std_per_run.to_csv(f'{result_directory}\\{run_of_interest}_std.csv')